# Site
# repository: p16pyla/resume-sw
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dionisis Pylarinos
title: This is my Resume
email: dionisis_7g7@hotmail.gr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dionisis-pylarinos-585694283
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
          # - title: CvPdf
     #  icon: fab fa-github
     #  url: https://p16pyla.github.io/cv-1/pdf/cv.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: profile3.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Dionisis, and I was born in 1998. I completed my undergraduate studies in Informatics at Ionian University and a Masterâ€™s degree in Digital Systems Security from the University of Piraeus. My native language is Greek, and I am fluent in English, holding the NOCN Level 1 Certificate in ESOL International. I have a strong interest in the field of Cybersecurity, particularly in penetration testing. I am passionate about identifying and analyzing vulnerabilities, assessing potential risks, and developing effective strategies to strengthen system resilience.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University projects
        # link: https://p16pyla.github.io/cv-1/pdf/cv.pdf
        # link_text: Project Cv Pdf
        # additional_links:
        # - title:  sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: https://p16pyla.github.io/cv-1/pdf/cv.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The most intrested for me
        description: | # this will include new lines to allow paragraphs
               Ionian University: I have completed quite a few security themed projects most of them involved achieving basic security attacks. 
               
               Ionian University: My thesis was about security with a theoretical background, the title was "Issues and discrepancies in the implementation of information security incident response strategies and the role of the human factor"
               
               Univeristy of Piraeus: I completed a large coursework related to applied cryptography, Security Assessment and Exploitation of Weaknesses, Network Security, Mobile Internet Security, Digital Forensics and Security on the World Wide Web. Also, in a more theoretical level, I dealt with legislative aspects around security, such as ISO,NIST and GDPR.
               
               Univeristy of Piraeus: I have completed my masterâ€™s thesis, titled â€œCTF Forensic Challengesâ€, in which I designed a series of hands-on forensic Capture The Flag challenges. One challenge I particularly enjoyed creating focuses on log analysis of a machine infected with malware â€” the objective is to analyze logs, reconstruct the attack timeline, and extract indicators of compromise to drive forensic conclusions.
               
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SOC Analyst â€” KMICRO (California, USA) November 2023 â€“ Present
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        quote: > 
        description: | # this will include new lines to allow paragraphs
            I am currently working as a Security Operations Center (SOC) Analyst at KMICRO, a cybersecurity firm based in California. My responsibilities included monitoring SIEM alerts and security telemetry, performing triage and incident validation, conducting log and host-based analysis, and coordinating escalations to incident response teams. I regularly applied threat-hunting techniques to identify suspicious activity, produced actionable incident reports and remediation recommendations.

            In my free time I practice on Hack The Box, currently working on [ðŸ“˜ Active Directory Penetration Tester path](https://academy.hackthebox.com/path/preview/active-directory-penetration-tester){:target="_blank"} 
  - tittle: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ionian University
        caption: 2016 - 2022
        sub_title: BSc Computer Science
        quote: >
          The first Greek University, the Ionian Academy, was founded in Corfu in 1824 and was the first modern-day Greek school of modern times and the academy of the United States of the Ionian Islands. The Department of Informatics has been operating since the academic year 2004-05. The subject of the Department is both theoretical and applied Informatics.
        description: | # this will include new lines to allow paragraphs
         Ionian University gave me knowledge and helped me improve my studying skills. I think the most important thing I gained was how to work on complicated tasks and other difficulties I faced, like security or code problems. All this research was quite a challenge but I finally managed to solve everything by efficiently using the knowledge I gained.
      - layout: top-middle
        title: University of Pireaus
        caption: 2022 - 2024
        sub_title: Digital Systems Security Department
        quote: >  
         This university is the second-oldest business school established in Greece, while the Department of Banking and Financial Management is the country's oldest academic department in the area of finance
        description: At the University of Piraeus I managed to work under strict deadlines and the most important thing I learned  is that in the field of security you have to constantly adapt to new data and new technologies and not rest on what is already known.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Other:
      
      [ðŸ“„ View My Masterâ€™s Thesis (PDF)](./mthesis.pdf)
      [ðŸ“„ View My Undergraduate Thesis (docx)](./pthesis.docx)
      
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
